# Custom Language File for Launcher Customizer

[ejs.app]
title = "Hasta Studios Launcher"

[ejs.landing]
mediaGitHubURL = "https://zelthoriaismp.cloud"
mediaTwitterURL = "https://x.com/AuroraVitaeSMP"
mediaInstagramURL = "https://www.tiktok.com/@auroravitaesmp"
mediaYouTubeURL = "https://www.youtube.com/@AuroraVitaeSMP"
mediaDiscordURL = "https://discord.gg/avsmp"

[ejs.settings]
sourceGithubLink = "https://github.com/oAccel/Auro"
supportLink = "https://github.com/oAccel/Auro/issues"
selectLanguage = "Select a Language"
changeLanguageTitle = "Change the launcher language"
changeLanguageDesc = "You can change the language in the list below. This text will not change if you change the language so you can find your wayback here to change it back"

[ejs.welcome]
welcomeHeader = "Seja bem-vindo(a) novo Assente!"
welcomeDescription = "É com muito prazer que apresentamos o Aurora Vitae Launcher, disponível somente aos dignos de coração"
welcomeDescCTA = "Desejar embarcar nessa história?"
welcome.continueButton = "Prosseguir"

[ejs.overlay]
changedLanguageHeader = "You changed the previous language"